In [1]:
import pandas as pd

In [3]:
data = {
    'name' : ['khizar', 'mudassir', 'mudassir', 'zoya'],
    'age' : [24, 18, 18, 13],
    'class' : ['graduated', '12th class', '12th class', '6th class']
}

df = pd.DataFrame(data)

In [4]:
df

       name  age       class
0    khizar   24   graduated
1  mudassir   18  12th class
2  mudassir   18  12th class
3      zoya   13   6th class

In [5]:
df.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
df.duplicated().sum()

np.int64(1)

In [7]:
df.drop_duplicates(keep = 'first')

       name  age       class
0    khizar   24   graduated
1  mudassir   18  12th class
3      zoya   13   6th class

In [9]:
df.drop_duplicates(inplace = True)

In [10]:
df

       name  age       class
0    khizar   24   graduated
1  mudassir   18  12th class
3      zoya   13   6th class

In [11]:
import seaborn

df = seaborn.load_dataset('titanic')

In [12]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [14]:
df.duplicated().sum()

np.int64(107)

In [16]:
print(f'Rows = {df.shape[0]}')

Rows = 891

In [17]:
df.drop_duplicates(keep = 'first', inplace = True)

In [18]:
print(f'Rows = {df.shape[0]}')

Rows = 784