In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame({'name' : ['Kharoos Insaan', 'Muddi Kinnu', 'Zoya Pakori', 'B Phatoo', 'Kali Peli Taxi']})
df

             name
0  Kharoos Insaan
1     Muddi Kinnu
2     Zoya Pakori
3        B Phatoo
4  Kali Peli Taxi

In [4]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['en_name'] = le.fit_transform(df['name'])

In [5]:
df

             name  en_name
0  Kharoos Insaan        2
1     Muddi Kinnu        3
2     Zoya Pakori        4
3        B Phatoo        0
4  Kali Peli Taxi        1

In [6]:
df = pd.read_csv(r'Employee.csv')

In [7]:
df.head()

               Name         City  Salary  Gender
0       James Smith     New York   72000    Male
1      Maria Garcia  Los Angeles   68000  Female
2     David Johnson      Chicago   55000    Male
3       Sarah Brown      Houston   61000  Female
4  Michael Williams      Phoenix   59000    Male

In [8]:
df['en_Name'] = le.fit_transform(df['Name'])

In [9]:
df.head()

               Name         City  Salary  Gender  en_Name
0       James Smith     New York   72000    Male       22
1      Maria Garcia  Los Angeles   68000  Female       33
2     David Johnson      Chicago   55000    Male       12
3       Sarah Brown      Houston   61000  Female       46
4  Michael Williams      Phoenix   59000    Male       37