In [21]:
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [22]:
df = pd.read_csv(r'Employee.csv')
df.head(3)

            Name         City  Salary  Gender
0    James Smith     New York   72000    Male
1   Maria Garcia  Los Angeles   68000  Female
2  David Johnson      Chicago   55000    Male

In [23]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [24]:
df['Gender'].nunique()

2

In [25]:
df.isnull().sum()

Name      0
City      0
Salary    0
Gender    0
dtype: int64

In [26]:
en_pandas = pd.get_dummies(df['Gender'], drop_first = True, dtype = int)
en_pandas.head()

   Male
0     1
1     0
2     1
3     0
4     1

In [30]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output = False, drop = 'first')

df['is_Male'] = ohe.fit_transform(df[['Gender']]).astype(int)

In [31]:
df.head()

               Name         City  Salary  Gender  is_Male
0       James Smith     New York   72000    Male        1
1      Maria Garcia  Los Angeles   68000  Female        0
2     David Johnson      Chicago   55000    Male        1
3       Sarah Brown      Houston   61000  Female        0
4  Michael Williams      Phoenix   59000    Male        1